apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice
  labels:
    app: authservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
        - name: authservice
          image: ${ECR_REGISTRY_DEV}/authservice:${GITHUB_SHA}
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: "travelhub-dev-authservice.cwfag2842c2y.us-east-1.rds.amazonaws.com"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "authservice_db"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: authservice-db-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authservice-db-secret
                  key: DB_PASSWORD
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
