apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking
  labels:
    app: booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking
  template:
    metadata:
      labels:
        app: booking
    spec:
      containers:
        - name: booking
          image: ${ECR_REGISTRY_DEV}/booking:${GITHUB_SHA}
          ports:
            - containerPort: 8000
          env:
          - name: BOOKING_DB_MODE
            value: postgres
          - name: CATALOG_SERVICE_URL
            value: http://catalog/catalog
          - name: PAYMENT_SERVICE_URL
            value: http://payment
          - name: PAYMENT_MODE
            value: wompi
          - name: RABBITMQ_HOST
            value: rabbitmq-broker
          - name: RABBITMQ_PORT
            value: "5672"
          - name: RABBITMQ_USER
            value: guest
          - name: RABBITMQ_PASS
            value: guest
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: booking-db-secret
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: booking-db-secret
                key: DB_PORT
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: booking-db-secret
                key: DB_NAME
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: booking-db-secret
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: booking-db-secret
                key: DB_PASSWORD
          startupProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 5
            failureThreshold: 24
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
