apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
  labels:
    app: catalog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog
        image: 962273458546.dkr.ecr.us-east-1.amazonaws.com/catalog:1.0.0
        ports:
        - containerPort: 80
