apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: ${ECR_REGISTRY_DEV}/notification:${GITHUB_SHA}
          ports:
            - containerPort: 8000
          env:
            - name: NOTIFICATION_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: notification-db-secret
                  key: DB_HOST
            - name: NOTIFICATION_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: notification-db-secret
                  key: DB_PORT
            - name: NOTIFICATION_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: notification-db-secret
                  key: DB_NAME
            - name: NOTIFICATION_DB_USER
              valueFrom:
                secretKeyRef:
                  name: notification-db-secret
                  key: DB_USER
            - name: NOTIFICATION_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-db-secret
                  key: DB_PASSWORD
            - name: RABBITMQ_HOST
              value: rabbitmq-broker
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              value: guest
            - name: RABBITMQ_PASS
              value: guest
            - name: REDIS_HOST
              value: redis-db
          startupProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 5
            failureThreshold: 24
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
