from enum import Enum
from dataclasses import dataclass

class EstadoSaga(Enum):
    EN_PROCESO = "EN_PROCESO"
    PAUSADA_ESPERANDO_HOTEL = "PAUSADA_ESPERANDO_HOTEL"
    COMPLETADA = "COMPLETADA"
    COMPENSANDO = "COMPENSANDO"
    COMPENSACION_EXITOSA = "COMPENSACION_EXITOSA"
    COMPENSACION_FALLIDA = "COMPENSACION_FALLIDA"

class TipoMensajeSaga(Enum):
    COMANDO_EMITIDO = "COMANDO_EMITIDO"
    EVENTO_RECIBIDO = "EVENTO_RECIBIDO"
    COMPENSACION_EMITIDA = "COMPENSACION_EMITIDA"
