apiVersion: v1
kind: Namespace
metadata:
  name: travelhub
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-admin-secret
  namespace: travelhub
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: authservice-app-secret
  namespace: travelhub
type: Opaque
stringData:
  SECRET_KEY: local-dev-secret-key
---
apiVersion: v1
kind: Secret
metadata:
  name: authservice-db-secret
  namespace: travelhub
type: Opaque
stringData:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: authservice_db
  DB_USER: authservice_app
  DB_PASSWORD: authservice_dev
---
apiVersion: v1
kind: Secret
metadata:
  name: booking-db-secret
  namespace: travelhub
type: Opaque
stringData:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: booking_db
  DB_USER: booking_app
  DB_PASSWORD: booking_dev
---
apiVersion: v1
kind: Secret
metadata:
  name: catalog-db-secret
  namespace: travelhub
type: Opaque
stringData:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: catalog_db
  DB_USER: catalog_app
  DB_PASSWORD: catalog_dev
---
apiVersion: v1
kind: Secret
metadata:
  name: search-db-secret
  namespace: travelhub
type: Opaque
stringData:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: search_db
  DB_USER: search_app
  DB_PASSWORD: search_dev
